name: orderease
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-56.0.dev <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloudinary_public: ^0.23.1
  file_picker: ^7.0.2
  charts_flutter: ^0.12.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  lottie: ^2.3.2
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher icon"
  ios: true
  image_path : "assets/waiter.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/waiter.png
